/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

/**
 *
 * @author varsh
 */
public class issue extends javax.swing.JFrame {

    /**
     * Creates new form issue
     */
    public issue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 204, 51));
        l2.setText("Book ID");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 99, -1));

        l3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 204, 51));
        l3.setText("Student ID");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 99, -1));

        l4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 204, 51));
        l4.setText("Issue Date");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 107, -1));

        l5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 204, 51));
        l5.setText("Due Date");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 99, -1));

        tf1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 190, -1));

        tf2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 190, -1));
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 190, 30));
        getContentPane().add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 190, 30));

        b1.setBackground(new java.awt.Color(255, 204, 51));
        b1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(102, 103, 105));
        b1.setText("Issue");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        b2.setBackground(new java.awt.Color(255, 204, 51));
        b2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 103, 105));
        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 100, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/photos/Issue.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
