/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author varsh
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        t5 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(102, 103, 105));
        l1.setText("Name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 80, 30));

        l2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(102, 103, 105));
        l2.setText("Student ID");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 110, -1));

        l4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(102, 103, 105));
        l4.setText("Department");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        l5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        l5.setForeground(new java.awt.Color(102, 103, 105));
        l5.setText("Semester");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        t1.setBackground(new java.awt.Color(204, 204, 204));
        t1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 210, 30));

        t2.setBackground(new java.awt.Color(204, 204, 204));
        t2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 210, 30));

        b1.setBackground(new java.awt.Color(102, 103, 105));
        b1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 204, 51));
        b1.setText("Save");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 80, -1));

        b2.setBackground(new java.awt.Color(102, 103, 105));
        b2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 204, 51));
        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 600, 90, -1));

        t5.setBackground(new java.awt.Color(204, 204, 204));
        t5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 440, 210, 30));

        t4.setBackground(new java.awt.Color(204, 204, 204));
        t4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 210, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/photos/13.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        t3.setBackground(new java.awt.Color(204, 204, 204));
        t3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 210, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            
               // Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/varsha?", "root", "");
            System.out.println("Connected successfully!");

            Statement stmt = conn.createStatement();
            String sql = "INSERT INTO `students`(`ID`, `Name`, `dept`, `semester`) VALUES ('"+t1.getText()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"')";
            ResultSet rs = stmt.executeQuery(sql);
            JOptionPane.showMessageDialog(null, rs);

          stmt.close();
            conn.close();
        } catch (Exception humair) {
            JOptionPane.showMessageDialog(null, humair.getMessage());
        }
        
        
        
        
        
        //new issue_view().setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
